/*.$file${.::Src::UartDriver.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: LwipDriver.qm
* File:  ${.::Src::UartDriver.c}
*
* This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::Src::UartDriver.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "CommDriver.h"
#include "string.h"
#include "stdlib.h"
#include "stdio.h"


#define OS_TICKS_PER_SEC 2

extern UART_HandleTypeDef huart3;

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::UartDriver} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::UartDriver} ......................................................*/
/*.${AOs::UartDriver::ctor} ................................................*/
void UartDriver_ctor(UartDriver * const me) {
    QActive_ctor(&me->super, (QStateHandler)&UartDriver_initial);
    QTimeEvt_ctorX(&me->te,&me->super,UART_PROCESS_SIG,0U);
}

/*.${AOs::UartDriver::SM} ..................................................*/
QState UartDriver_initial(UartDriver * const me, void const * const par) {
    /*.${AOs::UartDriver::SM::initial} */
    QActive_subscribe((QActive *)me, UART_TX_SIG);
    QActive_subscribe((QActive *)me, UART_RX_SIG);
    return Q_TRAN(&UartDriver_UartMngr);
}
/*.${AOs::UartDriver::SM::UartMngr} ........................................*/
QState UartDriver_UartMngr(UartDriver * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::UartDriver::SM::UartMngr} */
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->te, OS_TICKS_PER_SEC/2, OS_TICKS_PER_SEC/2);
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::UartDriver::SM::UartMngr} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->te);
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::UartDriver::SM::UartMngr::UART_PROCESS} */
        case UART_PROCESS_SIG: {
            __NOP();
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::UartDriver::SM::UartMngr::UART_RX} */
        case UART_RX_SIG: {
            static uint16_t receive_num=0;
            receive_num++;
            char temptext[20];
            strncpy(temptext, ((TextEvt const *)e)->text,Q_DIM(temptext));
            HAL_UART_Transmit(&huart3,(uint8_t *)temptext,sizeof(temptext),10);
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::UartDriver::SM::UartMngr::UART_TX} */
        case UART_TX_SIG: {
            char temptext[MAX_TEXT_LEN];
            uint16_t size=0;
            size = sprintf(temptext,((TextEvt const *)e)->text);
            __NOP();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${AOs::UartDriver} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/**
  * @brief  Rx Transfer completed callback.
  * @param  huart UART handle.
  * @retval None
  */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
  /* Prevent unused argument(s) compilation warning */
  UNUSED(huart);

 // QActive * const AO_UartDriver;
  HAL_GPIO_TogglePin(LD1_GPIO_Port,LD1_Pin);

  static uint16_t receive_num=0;
  receive_num++;

  TextEvt *te = Q_NEW(TextEvt, UART_RX_SIG);
  strncpy(te->text,(char *)huart->pRxBuffPtr,Q_DIM(te->text));
  QF_PUBLISH((QEvt *)te, AO_UartDriver);

  __NOP();
}






