/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stdlib.h"
#include "Shape.h"
#include "Rectangle.h"



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

Shape s1; 		/*Static allocation*/
Rectangle r1;	/*Static allocation*/
uint32_t a;



//#define       TASK_STK_SIZE            512
//#define       N_TASKS                   10
//
//
//OS_STK        TaskStk[N_TASKS][TASK_STK_SIZE];
//OS_STK        TaskStartStk[TASK_STK_SIZE];
//char          TaskData[N_TASKS];
//OS_EVENT     *RandomSem;


void  TaskStart (void *pdata);

int main(void)
{
	Shape s2; /* Automatic allocation*/
	Shape *ps3 = malloc(sizeof(Shape)); /*dynamic allocation*/

	Shape_ctor(&s1, 1, 2);
	Shape_ctor(&s2, 3, 4);
	Shape_ctor(ps3,  5, 6);

	Rectangle_ctor((Rectangle *)ps3,5, 6, 10, 13);
	Rectangle_ctor(&r1,1,2,15,10);

	Shape const *graph[]= {
			&s1,
			(Shape *)&r1,
			ps3,
			(Shape *)0
	};

	drawGraph(graph);

	Shape_moveBy(&s1, 7, 8);
	Shape_moveBy(&s2, 9, 10);
	Shape_moveBy(ps3, -1, -2);

	a = Rectangle_area(&r1);


	free(ps3);

//	OSTaskCreate(TaskStart, (void *)0, &TaskStartStk[TASK_STK_SIZE - 1], 0);



    /* Loop forever */
	for(;;);
}



void  TaskStart (void *pdata)
{

	while(1){

	}

}
