/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define MAX_CAPACITY 100

static uint8_t Memory_Pool[MAX_CAPACITY] = {0};

typedef struct {
	uint32_t *start_addr;
	uint32_t  mem_size;
	uint32_t *end_add;
}m_pool;

typedef struct {
	char msg[20];
}Text;


void Create_mem(m_pool *temp,(uint32_t)sizeof(struct x));
_Bool Alan_Tara(uint32_t size);

int main(void)
{
	Text a1;
    /* Loop forever */

	_Bool result = Alan_Tara(sizeof(a1));
	for(;;);
}


void Create_mem(m_pool *temp,(uint32_t)sizeof(struct x)){

}


_Bool Alan_Tara(uint32_t size){

	uint32_t memcnt = 0;
	_Bool result = 1;

	for(uint32_t i=0;i<MAX_CAPACITY;i++){

		  if(Memory_Pool[i] == 0){
			  memcnt++;
		  }
		  else
		  {
			  if(memcnt >= size){
				  result = 1;
			  }
			  else{
				  result = 0;
			  }

			  memcnt = 0;
		  }
	}

	return result;
}
