/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stdlib.h"
#include "freertos_ao.h"
#include "task.h"
#include "TimeBomb.h"
#include "stm32f407xx_gpio_driver.h"


/*********************************************************************
 * @fn      		  - Led_Init
 *
 * @brief             -	Led configuration function
 *
 * @param	          -	none
 * @param             - none
 * @param             - none
 *
 * @return            - void
 *
 * @Note              - This function configures clock and modes etc.. for connected led gpio ports.
 */
void Led_Init(void);


/*********************************************************************
 * @fn      		  - Button_Init
 *
 * @brief             -	Button configuration function
 *
 * @param	          -	none
 * @param             - none
 * @param             - none
 *
 * @return            - void
 *
 * @Note              - This function configures clock and modes etc.. for connected button gpio ports.
 */
void Button_Init(void);



/* The TimeBomb AO ============================================================*/


StackType_t Stack_TimeBomb[configMINIMAL_STACK_SIZE]; 		/*Dedicated Active Object Stack Size*/
StaticTask_t TimeBombTaskBuffer;							/*Dedicated Active Object Task Buffer holds related task informations*/
static Event *TimeBomb_queue[10];							/*Dedicated Active Object Event Queue that holds event posted from different source and passes active object dispatcher function*/
static TimeBomb timebomb;								/*Dedicated Active Object Structure*/
Active *AO_TimeBomb = &timebomb.super;					/* ??? */


int main(void)
{
   Led_Init();															 	/*Led Configuration Function*/

   Button_Init();														 	/*Button Configuration Function*/

   TimeBomb_ctor(&timebomb);									 			/*TimeBomb constructor function*/

   Active_start(AO_TimeBomb,										 		/*TimeBomb Active Object*/
		        "BinkyButton",												/*Active Object Name*/
			    configMINIMAL_STACK_SIZE,									/*Stack Size of Related Active Object Dispatcher Task*/
				tskIDLE_PRIORITY,											/*Priority of Related Active Object Dispatcher Task*/
				Stack_TimeBomb,										 		/*Stack Array of Related Active Object Dispatcher Task*/
				&TimeBombTaskBuffer,										/*TaskBuffer of Related Active Object*/
				TimeBomb_queue,										 		/*Queue of Related Active Object*/
				sizeof(TimeBomb_queue)/sizeof(TimeBomb_queue[0])); 			/*Queue Size of Related Active Object*/

	vTaskStartScheduler();													/*RTOS Scheduler Start Function*/

    /* Loop forever */
	for(;;);																/*We never came here */
}



/*********************************************************************
 * @fn      		  - Led_Init
 *
 * @brief             -	Led configuration function
 *
 * @param	          -	none
 * @param             - none
 * @param             - none
 *
 * @return            - void
 *
 * @Note              - This function configures clock and modes etc.. for connected led gpio ports.
 */

void Led_Init(void){

	GPIO_Handle_t GpioLed;													/*Gpio Handle Structure is created with a "GpioLed" tag.*/

	GPIO_PeriClockControl(GPIOD,ENABLE);									/*GPIOD Peripheral Clock is Enabled*/

	GpioLed.pGPIOx = GPIOD;													/*GPIO Instance is assigned as "GPIOD"*/
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;					/*GPIO Pin mode is chosen as an output Mode*/
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;					/*GPIO Pin Speed is chosed as "Fast"*/
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;				/*GPIO Pin Output Type is chosen as PushPull*/
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;				/*GPIO Pull Up & PullDown Control is chosen as NoPullupNoPullDown which means the pin is in Floating State.*/

	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;					/*GPIO Pin Number is Chosen as "PIN_12"*/
	GPIO_Init(&GpioLed);													/*GPIO Pin Configured as configuration settings above*/

	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;					/*GPIO Pin Number is Chosen as "PIN_13"*/
	GPIO_Init(&GpioLed);													/*GPIO Pin Configured as configuration settings above*/

	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;					/*GPIO Pin Number is Chosen as "PIN_14"*/
	GPIO_Init(&GpioLed);													/*GPIO Pin Configured as configuration settings above*/

	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;					/*GPIO Pin Number is Chosen as "PIN_15"*/
	GPIO_Init(&GpioLed);													/*GPIO Pin Configured as configuration settings above*/
}



/*********************************************************************
 * @fn      		  - Button_Init
 *
 * @brief             -	Button configuration function
 *
 * @param	          -	none
 * @param             - none
 * @param             - none
 *
 * @return            - void
 *
 * @Note              - This function configures clock and modes etc.. for connected button gpio ports.
 */
void Button_Init(void){

	GPIO_Handle_t GPIOBtn;													/*Gpio Handle Structure is created with a "GpioBtn" tag.*/

	GPIO_PeriClockControl(GPIOA,ENABLE);									/*GPIOA Peripheral Clock is Enabled*/

	GPIOBtn.pGPIOx = GPIOA;													/*GPIO Instance is assigned as "GPIOD"*/
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;					/*GPIO Pin mode is chosen as an input Mode*/
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;				/*GPIO Pull Up & PullDown Control is chosen as NoPullupNoPullDown which means the pin is in Floating State.*/
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;					/*GPIO Pin Number is Chosen as "PIN_12"*/
	GPIO_Init(&GPIOBtn);													/*GPIO Pin Configured as configuration settings above*/

}


/*********************************************************************
 * @fn      		  - vApplicationTickHook
 *
 * @brief             -	Tick Hook Function
 *
 * @param	          -	none
 * @param             - none
 * @param             - none
 *
 * @return            - void
 *
 * @Note              - This Function is Called From FreeRTOS Kernel in Every Dedicated Clock_Tick/Second.
 *						User Can Write Own Functions to Test RTOS Kernel System Working Performance or Period.
 */
void vApplicationTickHook( void ){
	//GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_15);	 /*GPIO_15 Pin is Toggled for Testing/Debugging Purpose*/
	App_TimeTickHook();							 /*TimeTickHook Function is called to process all Freertos/AO time events.*/
}

